export interface CharmConfig {
  id: string;
  name: string;
  description: string;
  collection: string;
  assetUrl: string;
  mass: number;
  ropeLength: number;
  stiffness: number;
}

export const CHARMS: CharmConfig[] = [
  {
    id: "batmanSymbol",
    name: "Batmansymbol",
    description: "A collectible charm from DC.",
    collection: "DC",
    assetUrl: "/charms/batmanSymbol.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "btsMemberFive",
    name: "btsMemberFive",
    description: "A collectible charm from BTS.",
    collection: "BTS",
    assetUrl: "/charms/btsMemberFive.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "btsMemberFour",
    name: "btsMemberFour",
    description: "A collectible charm from BTS.",
    collection: "BTS",
    assetUrl: "/charms/btsMemberFour.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "btsMemberOne",
    name: "btsMemberOne",
    description: "A collectible charm from BTS.",
    collection: "BTS",
    assetUrl: "/charms/btsMemberOne.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "btsMemberSeven",
    name: "btsMemberSeven",
    description: "A collectible charm from BTS.",
    collection: "BTS",
    assetUrl: "/charms/btsMemberSeven.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "btsMemberSix",
    name: "btsMemberSix",
    description: "A collectible charm from BTS.",
    collection: "BTS",
    assetUrl: "/charms/btsMemberSix.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "btsMemberThree",
    name: "btsMemberThree",
    description: "A collectible charm from BTS.",
    collection: "BTS",
    assetUrl: "/charms/btsMemberThree.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "btsMemberTwo",
    name: "btsMemberTwo",
    description: "A collectible charm from BTS.",
    collection: "BTS",
    assetUrl: "/charms/btsMemberTwo.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "captainAmericaShield",
    name: "Captainamericashield",
    description: "A collectible charm from Marvel.",
    collection: "Marvel",
    assetUrl: "/charms/captainAmericaShield.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "daruma",
    name: "daruma",
    description: "A collectible charm from Protection & Luck.",
    collection: "Protection & Luck",
    assetUrl: "/charms/daruma.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "drishtiBommai",
    name: "drishtiBommai",
    description: "A collectible charm from Protection & Luck.",
    collection: "Protection & Luck",
    assetUrl: "/charms/drishtiBommai.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "flash",
    name: "Flash",
    description: "A collectible charm from DC.",
    collection: "DC",
    assetUrl: "/charms/flash.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "greenLanternRing",
    name: "Greenlanternring",
    description: "A collectible charm from DC.",
    collection: "DC",
    assetUrl: "/charms/greenLanternRing.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "hamsa",
    name: "hamsa",
    description: "A collectible charm from Protection & Luck.",
    collection: "Protection & Luck",
    assetUrl: "/charms/hamsa.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "hulkFist",
    name: "Hulkfist",
    description: "A collectible charm from Marvel.",
    collection: "Marvel",
    assetUrl: "/charms/hulkFist.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "ironManHelmet",
    name: "Ironmanhelmet",
    description: "A collectible charm from Marvel.",
    collection: "Marvel",
    assetUrl: "/charms/ironManHelmet.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "karuppuStatue",
    name: "karuppuStatue",
    description: "A collectible charm from Tamil Divine.",
    collection: "Tamil Divine",
    assetUrl: "/charms/karuppuStatue.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "nazar",
    name: "nazar",
    description: "A collectible charm from Protection & Luck.",
    collection: "Protection & Luck",
    assetUrl: "/charms/nazar.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "nimbuMirchi",
    name: "nimbuMirchi",
    description: "A collectible charm from Protection & Luck.",
    collection: "Protection & Luck",
    assetUrl: "/charms/nimbuMirchi.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "omSymbol",
    name: "omSymbol",
    description: "A collectible charm from Tamil Divine.",
    collection: "Tamil Divine",
    assetUrl: "/charms/omSymbol.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "spiderMan",
    name: "Spiderman",
    description: "A collectible charm from Marvel.",
    collection: "Marvel",
    assetUrl: "/charms/spiderMan.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "supermanShield",
    name: "Supermanshield",
    description: "A collectible charm from DC.",
    collection: "DC",
    assetUrl: "/charms/supermanShield.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "templeBell",
    name: "templeBell",
    description: "A collectible charm from Tamil Divine.",
    collection: "Tamil Divine",
    assetUrl: "/charms/templeBell.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "thorHammer",
    name: "Thorhammer",
    description: "A collectible charm from Marvel.",
    collection: "Marvel",
    assetUrl: "/charms/thorHammer.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "vel",
    name: "vel",
    description: "A collectible charm from Tamil Divine.",
    collection: "Tamil Divine",
    assetUrl: "/charms/vel.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "vinayagarCoin",
    name: "vinayagarCoin",
    description: "A collectible charm from Tamil Divine.",
    collection: "Tamil Divine",
    assetUrl: "/charms/vinayagarCoin.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
  {
    id: "wonderWomanEmblem",
    name: "Wonderwomanemblem",
    description: "A collectible charm from DC.",
    collection: "DC",
    assetUrl: "/charms/wonderWomanEmblem.svg",
    mass: 2.0,
    ropeLength: 150,
    stiffness: 0.9,
  },
];

export function getCharmById(id: string): CharmConfig | undefined {
  const charm = CHARMS.find((c) => c.id === id);
  if (!charm) {
    console.warn(`Unknown charm: ${id}`);
  }
  return charm;
}
